import { Input } from '@nextui-org/react';
import { hoge, User } from '@wiscro/common';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useTest } from '../hooks/useTest';

const Home: NextPage = () => {
  console.log(hoge, new User('hoge'));
  const { data } = useTest();
  console.log(data);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Input placeholder="Next UI" />
      </main>
    </div>
  );
};

export default Home;
