import { Input, Spacer } from '@nextui-org/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { useOgp } from '../hooks/Ogp';

const Home: NextPage = () => {
  const [url, setUrl] = useState('');
  const { data: ogp } = useOgp(url);
  console.log(ogp, 15);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Spacer y={3} />
        <Input onChange={(e) => setUrl(e.target.value)} placeholder="Next UI" />
      </main>
    </div>
  );
};

export default Home;
