import { Input, Spacer, Text } from '@nextui-org/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { OgpCard } from '../components/domains/Ogp/OgpCard';
import { useOgp } from '../hooks/Ogp';

const Home: NextPage = () => {
  const [url, setUrl] = useState('');
  const { data: ogp } = useOgp(url);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ width: '500px', margin: '0 auto' }}>
        <Spacer y={5} />
        <Text h2>Welcome to Wiscro !</Text>
        <Spacer y={3} />
        <Input onChange={(e) => setUrl(e.target.value)} placeholder="type url..." bordered fullWidth />
        <Spacer y={1} />
        {ogp && <OgpCard ogp={ogp} />}
      </main>
    </div>
  );
};

export default Home;
